export default {
  font: {
    family: "Montserrat, sans-serif",
    light: 300,
    normal: 400,
    bold: 600,
    extraBold: 800,
    sizes: {
      xsmall: "1.2rem",
      small: "1.4rem",
      medium: "1.6rem",
      large: "2.0rem",
      xlarge: "2.8rem",
      huge: "5.2rem",
    },
  },
  colors: {
    purple: "#A141EB",
    purple_dark: "#7928B7",
    yellow: "#E1A607",
    blue: "#0CBFE2",
    background: "#F1F1F1",
    dark: "#5B5B5B",
    white: "#FFFFFF",
  },
  spacings: {
    xxsmall: "0.8rem",
    xsmall: "1.6rem",
    small: "2.4rem",
    medium: "3.2rem",
    large: "4.0rem",
    xlarge: "4.8rem",
    xxlarge: "5.6rem",
  },
} as const;
